name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10]
    env:
      PORT: 5000
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install backend dependencies
      working-directory: ./backend
      run: pnpm install
    - name: Build backend
      working-directory: ./backend
      run: pnpm run build
    - name: Test backend
      working-directory: ./backend
      run: pnpm run test
      